### ISSUE TITLE
Thi plugin doesn't work with Javascript projects

### ISSUE THREAD

**Issue by leosuncin** [ifiokjr/prettier-plugin-sorted#6]
This plugin apparently doesn't work with Javascript projects, Prettier enter in a look like infinite loop because unless I kill it the process throw a `RangeError: Maximum call stack size exceeded` due [tsconfig-resolver](https://github.com/ifiokjr/tsconfig-resolver)

<details>
<summary>Stacktrace</summary>
<pre>
[error] pages/index.js: RangeError: Maximum call stack size exceeded
[error]     at Object.existsSync (fs.js:240:20)
[error]     at walkForTsConfig (/tmp/tmp.E5nYbj2EY6/prettier-plugin-sorted-issue-2/node_modules/tsconfig-resolver/dist/tsconfig-resolver.cjs.development.js:72:10)
[error]     at walkForTsConfig (/tmp/tmp.E5nYbj2EY6/prettier-plugin-sorted-issue-2/node_modules/tsconfig-resolver/dist/tsconfig-resolver.cjs.development.js:82:10)
[error]     at walkForTsConfig (/tmp/tmp.E5nYbj2EY6/prettier-plugin-sorted-issue-2/node_modules/tsconfig-resolver/dist/tsconfig-resolver.cjs.development.js:82:10)
[error]     at walkForTsConfig (/tmp/tmp.E5nYbj2EY6/prettier-plugin-sorted-issue-2/node_modules/tsconfig-resolver/dist/tsconfig-resolver.cjs.development.js:82:10)
[error]     at walkForTsConfig (/tmp/tmp.E5nYbj2EY6/prettier-plugin-sorted-issue-2/node_modules/tsconfig-resolver/dist/tsconfig-resolver.cjs.development.js:82:10)
[error]     at walkForTsConfig (/home/user/prettier-plugin-sorted-issue-2/prettier-plugin-sorted-issue-2/node_modules/tsconfig-resolver/dist/tsconfig-resolver.cjs.development.js:82:10)
[error]     at walkForTsConfig (/home/user/prettier-plugin-sorted-issue-2/prettier-plugin-sorted-issue-2/node_modules/tsconfig-resolver/dist/tsconfig-resolver.cjs.development.js:82:10)
[error]     at walkForTsConfig (/home/user/prettier-plugin-sorted-issue-2/prettier-plugin-sorted-issue-2/node_modules/tsconfig-resolver/dist/tsconfig-resolver.cjs.development.js:82:10)
[error]     at walkForTsConfig (/home/user/prettier-plugin-sorted-issue-2/prettier-plugin-sorted-issue-2/node_modules/tsconfig-resolver/dist/tsconfig-resolver.cjs.development.js:82:10)
</pre>
</details>

Repo with the issue: https://github.com/leosuncin/prettier-plugin-sorted-issue-6

**Comment by ifiokjr** [comment]
I don't actually use this plugin any more. I'd recommend switching to [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort).
